### ISSUE TITLE
Multi Database Modules works on 3.0.1 but not on 3.1.1

### ISSUE THREAD

**Issue by hister** [Raizlabs/DBFlow#979]
DBFlow Version: 3.1.1
Bug: Multi module no longer works

Description: 
when using version 3.0.1 multi module works fine but when updated to version 3.1.1 i get this error and it can't find the generated database holder class (it exists in android studio i can open it but can't build the project)

```
Warning:File for type 'com.raizlabs.android.dbflow.config.FordDatabaseFord_Database' created in the last round will not be subject to annotation processing.
Warning:File for type 'com.raizlabs.android.dbflow.config.FordModuleGeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
Warning:The following options were not recognized by any processor: '[targetModuleName]'
```

**Comment by trevjonez** [comment]
Those are simply warning and will not cause your build to fail. Because of the way the Filer api works you can not overwrite a file that was generated in previous generation rounds.

As such these classes that are deferred to the final round need to be aware of all models, converters etc are not generated until the final round of processing. The generated classes them selves do not have annotations that are inputs to other tools so it causes no issue.

**Comment by hister** [comment]
so what is the reason that compiler can't file the generated helper class when trying to build the project ?
this is the exact error given in gradle

```
error: cannot find symbol
import com.raizlabs.android.dbflow.config.FordGeneratedDatabaseHolder;
                                         ^
  symbol:   class FordGeneratedDatabaseHolder
  location: package com.raizlabs.android.dbflow.config
warning: File for type 'com.raizlabs.android.dbflow.config.FordDatabaseFord_Database' created in the last round will not be subject to annotation processing.
warning: File for type 'com.raizlabs.android.dbflow.config.FordGeneratedDatabaseHolder' created in the last round will not be subject to annotation processing.
warning: The following options were not recognized by any processor: '[targetModuleName]'
1 error
2 warnings

 FAILED
```

this is what I', trying to do and the compiler doesn't seem to be able to find FordGeneratedDatabaseHolder class; but i can see that the file is generated.

`FlowManager.initModule(FordGeneratedDatabaseHolder.class);`

i tested this on 2 different projects and the same thing happened but it works fine on version 3.0.1

I can't figure out what causes the problem

**Comment by hister** [comment]
Any follow up on this ?

**Comment by agrosner** [comment]
have you tried 4.0.0-beta3?

**Comment by agrosner** [comment]
will reopen if issue still persists on that version.

**Comment by jackwang1** [comment]
I'm running into this issue on 4.0.2. Using annotationProcessor instead of apt.

**Comment by yeduRaghav** [comment]
This issue exists for me.
I was using 3.0.1, wanted to update to 4.0.3 (yes, really behind, I know!).
I use annotation processor instead of the apt.

I have two separate GenertedDatabaseHolders, both build fine on version 3.0.1
I tried upgrading to 4.0.3.
The first databaseHolder builds, but the second one doesn't.

In order to find out which version update was causing the issue, I tried updating version one by one, towards 4.0.3 from builds 3.0.1.

It started to fail building the second database holder on 3.1.1 and version after.
Correct me if I am wrong, I suspect the second database holder failing to build is immaterial, and it might be the same issue, with annotation processor.

I shall try to revert and try using apt and upgrade to 4.0.3 and see if it works.

**Comment by andriipanasiuk** [comment]
I have the same issue.
DBFlow **4.0.2**
Using **annotationProcessor**, not _apt_
Gradle **2.3.0**

Module specific ModuleGeneratedDatabaseHolder.java file is generated in build/generated/source/apt/debug/com/raizlabs/android/dbflow/config along with EventDatabaseEvents_Database.java file.

**Comment by jackwang1** [comment]
Is there some cached documentation for 3.0.1? Would really like to have multiple modules over all the bug fixes and changes in 4.0.3.

**Comment by jackwang1** [comment]
Went back to 3.0.1, gradle 2.2.1 and apt since I need multiple modules. Still can't get multiple generated database holders.

@yeduRaghav or anyone else, do you have any sample code of it working?

**Comment by chaleao** [comment]
@jackwang1 is your configuration something similar the setup below?

build.gradle (app)

```
buildscript {
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}
```

build.gradle (Module 1)

```
apply plugin: 'com.neenbedankt.android-apt'

apt {
    arguments {
        targetModuleName 'Mod 1'
    }
}

def dbflow_version = "3.0.1"

```

build.gradle (Module 2)
```
apply plugin: 'com.neenbedankt.android-apt'

buildscript {
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    }
}

apt {
    arguments {
        targetModuleName 'Mod 2'
    }
}

def dbflow_version = "3.0.1"

```

then wherever you are setting up you dp from

```
  FlowManager.init(new FlowConfig.Builder(this)
                .addDatabaseHolder(Module1GeneratedDatabaseHolder.class)
                .addDatabaseHolder(Module2GeneratedDatabaseHolder.class)
                .build());

```

The setup on the project I'm working on it's similar the setup above and it's working with apt and dbflow version 3.0.1

**Comment by jackwang1** [comment]
I have the following structure:

Root build.gradle - what you have in app
app build.gradle - what you have in module 1
Module build.gradle - what you have in module 2

One requirement I have is app has module as dependency. Same problem I'm seeing with 4.0.3, which is database holder only generated for app, and not module.

**Comment by chaleao** [comment]
@jackwang1 are you building you FlowManager like below?

```
 FlowManager.init(new FlowConfig.Builder(this)
                .addDatabaseHolder(Module1GeneratedDatabaseHolder.class)
                .addDatabaseHolder(Module2GeneratedDatabaseHolder.class)
                .build());
```

**Comment by jackwang1** [comment]
Yes, though cannot add the second module since database holder for it is not generating.

**Comment by trevjonez** [comment]
the information in this issue thread is mostly un-actionable. When it comes to build failures like this your best bet would be to make a demo project that exhibits the issue. If it is a runtime issue fork and issue a pr with failing tests.

**Comment by jackwang1** [comment]
Was finally able to get 3.0.1 working with multiple modules. Seems ordering of dependencies in build.gradle matters.

@trevjonez Haven't looked at the unit tests, but [here's a repo](https://github.com/jackwang1/DBFlow-SQLCipher/releases) I quickly put together to show difference between 3.0.1 and 4.0.3.

**Comment by trevjonez** [comment]
@jackwang1 I made a small change to the timing that the processor outputs files. It is beyond me why it was necessary but should resolve your problem (assuming it gets merged). Until then you can target my develop snapshots. 

this patch file can be applied to your example project to show you what all I changed. 

[dbflow_mrp_fix.diff.txt](https://github.com/Raizlabs/DBFlow/files/1066651/dbflow_mrp_fix.diff.txt)

**Comment by jackwang1** [comment]
Thanks @trevjonez

**Comment by andriipanasiuk** [comment]
Thanks @trevjonez 
Your `develop-SNAPSHOT` version works great!
Looking forward for it being merged into RaizLabs production version.

**Comment by yeduRaghav** [comment]
@andriipanasiuk  @trevjonez @jackwang1  can anyone tell me how to use the `develop-snapshot` ?
I am what to do. Thank you!

**Comment by trevjonez** [comment]
the workaround that jackwang is using is to depend on a jitpack of my fork from the develop branch.
```
def dbflow_version = "develop-SNAPSHOT"
compile "com.github.trevjonez.DBFlow:dbflow:${dbflow_version}"
etc...
```

**Comment by jackwang1** [comment]
@yeduRaghav master branch of my example project is using develop-SNAPSHOT https://github.com/jackwang1/DBFlow-SQLCipher

**Comment by yeduRaghav** [comment]
Thank you guys, one last question, so this is equivalent to the latest DBFlow ?

**Comment by trevjonez** [comment]
as of about 8 days ago, yes.
