### ISSUE TITLE
Cannot find symbol class ...GeneratedDatabaseHolder

### ISSUE THREAD

**Issue by elsennov** [Raizlabs/DBFlow#783]
DBFlow Version: 3.0.0-beta6
Issue Kind (Bug, Question, Feature): Question

Please note if you are using Instant Run, there may be bugs where generated classes are not created. Ensure you are using
the [apt](https://bitbucket.org/hvisser/android-apt) or [kapt](http://blog.jetbrains.com/kotlin/2015/06/better-annotation-processing-supporting-stubs-in-kapt/) plugins and that incremental compilation is off.

Description: 
Hi, 
Error:(14, 42) error: cannot find symbol class SkyfishGeneratedDatabaseHolder
Skyfish is my module. It occurred after updated to 3.0.0-beta6. Previously, i used 3.0.0-beta1 and no problem.
Please help.

**Comment by elsennov** [comment]
I am using:
classpath 'com.android.tools.build:gradle:2.1.0'

**Comment by elsennov** [comment]
Please help @agrosner :)

**Comment by agrosner** [comment]
hmm. The class is never generated?

**Comment by agrosner** [comment]
or this is a library module you mean

**Comment by elsennov** [comment]
library module. Now i got this error message
<img width="1262" alt="screen shot 2016-05-03 at 10 39 03 am" src="https://cloud.githubusercontent.com/assets/7565601/14974160/4fee32bc-111b-11e6-8aa3-cf808cb1bd3d.png">

Do you have any idea?

**Comment by elsennov** [comment]
Skyfish is my library. The error occured when building the app.

**Comment by agrosner** [comment]
Looks like you're missing an import.

**Comment by elsennov** [comment]
Nope, the file is not generated in build folder

**Comment by carmas123** [comment]
With Rebuild project?

**Comment by elsennov** [comment]
Yes, i have rebuilt the project but no luck

**Comment by agrosner** [comment]
The warning gives it away. `The file for type ".....SkyfishGeneratedDatabaseHolder" created in the last round...` etc means that it was generated.

**Comment by darkyelox** [comment]
I have the same issue, the file is generated successfully and Android Studio does not marks error in my imports but when i try to rebuild the error persist and i cannot build nothing, this is happening me with apt, with kapt seems to work well, i tried all **4.0.0** beta versions until **beta5**, i tried to rollback to **3.1.1** and nothing works...

**Comment by chaleao** [comment]
+1

**Comment by AugustoAleGon** [comment]
I have the same issue here.

**Comment by neeraj76** [comment]
Faced the same issue.

**Comment by knnwulf** [comment]
Ensure you have a least the 3 dependencies on gradle:

apt "com.github.Raizlabs.DBFlow:dbflow-processor:$rootProject.ext.dbFlowVersion"
compile "com.github.Raizlabs.DBFlow:dbflow-core:$rootProject.ext.dbFlowVersion"
compile "com.github.Raizlabs.DBFlow:dbflow:$rootProject.ext.dbFlowVersion"

**Comment by onyx-hehai** [comment]
I have the same issue here.

**Comment by AugustoAleGon** [comment]
I solved the same issue stop using apt now is integrated with the gradle. Check the repositorie of apt in Bitbucket.
