### ISSUE TITLE
Encounter NoSuchMethodError when bump up DbFlow version from 3.0.0-beta5 to 4.2.3

### ISSUE THREAD

**Issue by laycui** [Raizlabs/DBFlow#1553]
DBFlow Version: 4.2.3

Bug or Feature Request: Bug

Description:
When I was bumping up the DbFlow version from 3.0.0-beta5 to 4.2.3, after resolving all the syntax errors, I have encounter this error, which leads to the failure of generating  _Table. The error message is:

Error:Execution failed for task ':MyProject:compileDevDebugJavaWithJavac'.
> java.lang.NoSuchMethodError: com.raizlabs.android.dbflow.annotation.Database.sqlHelperClass()Ljava/lang/Class;

When I was reading this [tutorial](https://guides.codepath.com/android/DBFlow-Guide), it says:

> Note: Make sure to remove any previous references of DBFlow if you are upgrading. The annotation processor has significantly changed for older versions. If you java.lang.NoSuchMethodError: com.raizlabs.android.dbflow.annotation.Table.tableName()Ljava/lang/String;, then you are likely to still have included the old annotation processor in your Gradle configuration.

I didn't quite get what this means, what exactly should I remove? Or there is some other issue might be involved? Thanks,
