### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics during processing

### ISSUE THREAD

**Issue by WonderCsabo** [Raizlabs/DBFlow#1417]
DBFlow Version: 4.1.0
Issue Kind (Bug, Question, Feature): Bug
 
Description:

We are getting the following error since updating DBFlow from 4.0.5 to 4.1.0 . This is a non-Kotlin Android project, here are the versions of the build tools (pretty much the latest stable):
```groovy
minSdkVersion 19
targetSdkVersion 25
buildToolsVersion '26.0.1'

classpath 'com.android.tools.build:gradle:2.3.3'

Gradle 4.1
```

This is the stacktrace printed at the beginning of the processing:
```java
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at com.raizlabs.android.dbflow.processor.DBFlowProcessor.init(DBFlowProcessor.kt)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 51 more
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        ... 61 more
```

A short Google search suggests to add the Kotlin runtime library to the classpath to resolve the error (which will translate to the processing path in the case of the end user of your library, like us).

**Comment by esotericpig** [comment]
I also got this error for v4.1.0.
The solution was to change my version back to 4.0.5.

This is all I'm using in my gradle files:

```
allprojects {
    repositories {
        jcenter()
        maven { url "https://www.jitpack.io" } // For DBFlow
    }
}
```

```
def dbflow_version = "4.1.0" // Change to 4.0.5 to work

dependencies {
    // ....
    // DBFlow
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
}
```

Looks like in 4.0.5, DBFlowProcessor was a Java file, and then it got changed to a Kotlin file.
The solution is to either make a Java file for it again or to require all projects to require Kotlin now.

https://github.com/Raizlabs/DBFlow/blob/4.0.5/dbflow-processor/src/main/java/com/raizlabs/android/dbflow/processor/DBFlowProcessor.java

**Comment by agrosner** [comment]
released. 4.1.1
