### ISSUE TITLE
Package com.raizlabs.dbflow.android.sqlcipher does not exist in beta 7

### ISSUE THREAD

**Issue by shobhik** [Raizlabs/DBFlow#1264]
DBFlow Version: 4.0.0-beta7, possible bug

So I updated my gradle import of dbflow from 4.0.0-beta5 to 4.0.0-beta7. I made the necessary changes to SQLCondition > Operator, etc. However, my import of SQLCipher does not seem to have worked. 

This is what the import looks like in Gradle:

```
   annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"

    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"

    compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'

```

The error in Gradle Build:
```
Error:(8, 45) error: package com.raizlabs.dbflow.android.sqlcipher does not exist

Error:(20, 42) error: cannot find symbol class SQLCipherOpenHelper

```

Hoping there is an easy workaround

**Comment by shobhik** [comment]
Update, found an iffy workaround:

```
    def dbflow_version = "4.0.0-beta7"
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:4.0.0-beta5"

```
Currently seems to work, though I wouldn't want a version mismatch like that long-term.

**Comment by agrosner** [comment]
try 4.0.1 and let me know of any issues. thank you.

**Comment by shobhik** [comment]
@agrosner 4.0.1 did not work for me, unfortunately. Here's the relevant current code:

```
def dbflow_version = "4.0.1"
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
    compile 'net.zetetic:android-database-sqlcipher:3.5.6@aar'

```

**Comment by shobhik** [comment]
@agrosner I just tried the same thing with 4.0.2 and got the same error as before. If I update my dbflow-core to 4.0.2 and keep my dbflow-sqlcipher at 4.0.0-beta5, I get a crash when I try to query or write to the DB:

```
java.lang.AbstractMethodError: abstract method "com.raizlabs.android.dbflow.structure.database.FlowCursor com.raizlabs.android.dbflow.structure.database.DatabaseWrapper.rawQuery(java.lang.String, java.lang.String[])"
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:58)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.load(ListModelLoader.java:44)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.load(ListModelLoader.java:15)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.load(ListModelLoader.java:37)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.load(ListModelLoader.java:15)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:36)
                                                                                         at com.raizlabs.android.dbflow.sql.queriable.ListModelLoader.load(ListModelLoader.java:25)
                                                                                         at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.queryList(BaseModelQueriable.java:61)
                                                                                         at com.raizlabs.android.dbflow.sql.language.Where.queryList(Where.java:237)
                                                                                         at com.simplebutneeded.android.assetpro.data.AssetDataSyncManager.getAllPrimaryLocations(AssetDataSyncManager.java:80)
                                                                                         at com.simplebutneeded.android.assetpro.selectors.LocationPrimarySelector.onCreate(LocationPrimarySelector.java:39)
                                                                                         at android.app.Activity.performCreate(Activity.java:6664)
                                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                                         at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by shobhik** [comment]
@agrosner I still encounter the "SQLCipher does not exist" when trying to compile with version 4.0.5

**Comment by agrosner** [comment]
I am not seeing the issue you're seeing. try this with version 4.0.5:
```
 annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
 compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
 compile "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
 compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
```

**Comment by shobhik** [comment]
So I run with dbflow-processor, dbflow-core, dbflow all set to 4.0.5 just fine. However, if I set dbflow-sqlcipher to 4.0.5, I get that error. 

```
    Error:(8, 45) error: package com.raizlabs.dbflow.android.sqlcipher does not exist`
    Error:(20, 42) error: cannot find symbol class SQLCipherOpenHelper
```

Here's my build.gradle code:
```
    dbflowVersion = "4.0.5"
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflowVersion}"
    compile "com.github.Raizlabs.DBFlow:dbflow-core:${dbflowVersion}"
    compile "com.github.Raizlabs.DBFlow:dbflow:${dbflowVersion}"
    compile "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflowVersion}"
```

**Comment by shobhik** [comment]
@agrosner Actually, I just fixed it. It turned out, my import for SQLCipherOpenHelper was using the following import statement:

`import com.raizlabs.dbflow.android.sqlcipher.SQLCipherOpenHelper;`

This worked in 4.0.0-beta5 but not in production 4.0.5. Changing it to...

`import com.raizlabs.android.dbflow.sqlcipher.SQLCipherOpenHelper;
`
...solved the problem. Maybe update the docs? Also, thanks for the help on this!
